### ISSUE TITLE
Malfunction since js-controller update to version 5.0.12

### ISSUE THREAD

**Issue by BlackTigga** [TA2k/ioBroker.wmswebcontrol#8]
Dear Adapter developer,

since I've updated IoBroker to js-controller 5.0.12 the wmswebcontrol doesn't work anymore.
Output from logfile:

`2023-09-24 08:18:25.186 - info: host.All-In-One-RasPi Restart adapter system.adapter.wmswebcontrol.0 because enabled
2023-09-24 08:18:55.804 - info: host.All-In-One-RasPi instance system.adapter.wmswebcontrol.0 started with pid 5697
2023-09-24 08:18:58.769 - error: host.All-In-One-RasPi Caught by controller[0]: node:internal/modules/cjs/loader:573
2023-09-24 08:18:58.771 - error: host.All-In-One-RasPi Caught by controller[0]: throw e;
2023-09-24 08:18:58.772 - error: host.All-In-One-RasPi Caught by controller[0]: ^
2023-09-24 08:18:58.773 - error: host.All-In-One-RasPi Caught by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/defaults' is not defined by "exports" in /opt/iobroker/node_modules/axios/package.json
2023-09-24 08:18:58.774 - error: host.All-In-One-RasPi Caught by controller[0]: at new NodeError (node:internal/errors:405:5)
2023-09-24 08:18:58.775 - error: host.All-In-One-RasPi Caught by controller[0]: at exportsNotFound (node:internal/modules/esm/resolve:359:10)
2023-09-24 08:18:58.775 - error: host.All-In-One-RasPi Caught by controller[0]: at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
2023-09-24 08:18:58.776 - error: host.All-In-One-RasPi Caught by controller[0]: at resolveExports (node:internal/modules/cjs/loader:567:36)
2023-09-24 08:18:58.776 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:636:31)
2023-09-24 08:18:58.777 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
2023-09-24 08:18:58.778 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
2023-09-24 08:18:58.779 - error: host.All-In-One-RasPi Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-09-24 08:18:58.779 - error: host.All-In-One-RasPi Caught by controller[0]: at require (node:internal/modules/cjs/helpers:121:18)
2023-09-24 08:18:58.780 - error: host.All-In-One-RasPi Caught by controller[0]: at Object. (/opt/iobroker/node_modules/axios-cookiejar-support/lib/index.js:8:40) {
2023-09-24 08:18:58.781 - error: host.All-In-One-RasPi Caught by controller[0]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2023-09-24 08:18:58.781 - error: host.All-In-One-RasPi Caught by controller[0]: }
2023-09-24 08:18:58.782 - error: host.All-In-One-RasPi Caught by controller[0]: Node.js v18.17.1
2023-09-24 08:18:58.783 - error: host.All-In-One-RasPi instance system.adapter.wmswebcontrol.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-09-24 08:18:58.784 - info: host.All-In-One-RasPi Restart adapter system.adapter.wmswebcontrol.0 because enabled
2023-09-24 08:19:29.670 - info: host.All-In-One-RasPi instance system.adapter.wmswebcontrol.0 started with pid 6606
2023-09-24 08:19:32.982 - error: host.All-In-One-RasPi Caught by controller[0]: node:internal/modules/cjs/loader:573
2023-09-24 08:19:32.984 - error: host.All-In-One-RasPi Caught by controller[0]: throw e;
2023-09-24 08:19:32.985 - error: host.All-In-One-RasPi Caught by controller[0]: ^
2023-09-24 08:19:32.986 - error: host.All-In-One-RasPi Caught by controller[0]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/defaults' is not defined by "exports" in /opt/iobroker/node_modules/axios/package.json
2023-09-24 08:19:32.987 - error: host.All-In-One-RasPi Caught by controller[0]: at new NodeError (node:internal/errors:405:5)
2023-09-24 08:19:32.987 - error: host.All-In-One-RasPi Caught by controller[0]: at exportsNotFound (node:internal/modules/esm/resolve:359:10)
2023-09-24 08:19:32.988 - error: host.All-In-One-RasPi Caught by controller[0]: at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
2023-09-24 08:19:32.989 - error: host.All-In-One-RasPi Caught by controller[0]: at resolveExports (node:internal/modules/cjs/loader:567:36)
2023-09-24 08:19:32.990 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._findPath (node:internal/modules/cjs/loader:636:31)
2023-09-24 08:19:32.991 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
2023-09-24 08:19:32.992 - error: host.All-In-One-RasPi Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
2023-09-24 08:19:32.993 - error: host.All-In-One-RasPi Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-09-24 08:19:32.994 - error: host.All-In-One-RasPi Caught by controller[0]: at require (node:internal/modules/cjs/helpers:121:18)
2023-09-24 08:19:32.994 - error: host.All-In-One-RasPi Caught by controller[0]: at Object. (/opt/iobroker/node_modules/axios-cookiejar-support/lib/index.js:8:40) {
2023-09-24 08:19:32.995 - error: host.All-In-One-RasPi Caught by controller[0]: code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2023-09-24 08:19:32.996 - error: host.All-In-One-RasPi Caught by controller[0]: }
2023-09-24 08:19:32.996 - error: host.All-In-One-RasPi Caught by controller[0]: Node.js v18.17.1
2023-09-24 08:19:32.997 - error: host.All-In-One-RasPi instance system.adapter.wmswebcontrol.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-09-24 08:19:32.999 - info: host.All-In-One-RasPi Restart adapter system.adapter.wmswebcontrol.0 because enabled
2023-09-24 08:20:03.594 - info: host.All-In-One-RasPi instance system.adapter.wmswebcontrol.0 started with pid 7524`

Please give a feedback how to solve this issue.
Thank you very much.

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 5.0.12
 - Node version: 18.18.0
 - Operating system: linux

**Comment by TA2k** [comment]
switch to beta repo and update to 0.0.6

**Comment by BlackTigga** [comment]
I'm not an expert, but I found the dialog to switch to beta repositories.
![2023-09-25_15h16_00](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/e939ff9a-0781-4ec9-a45e-3769ac813e30)

But in IoBroker I don't find any option for update to 0.0.6

![2023-09-25_15h19_35](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/a3382233-e5dc-4fda-9d77-83476a96e819)
![2023-09-25_15h20_00](https://github.com/TA2k/ioBroker.wmswebcontrol/assets/75884667/449e553a-ac8f-4f74-a10d-aa1232823ba3)


Could you please give me a hint how I can proceed the update process.

**Comment by TA2k** [comment]
Sollte morgen sichtbar sein oder über das Katzenssymbol via GitHub installieren

**Comment by BlackTigga** [comment]
@TA2k 
Hi, wird dieser Adapter auf längere Sicht "am Leben" bleiben? 
Ich habe jetzt mit der 0.0.6 Version Fehlermeldungen ([https://github.com/TA2k/ioBroker.wmswebcontrol/issues/12](url)) und weil ich nun nicht mehr weiter wusste, habe ich den Adapter deinstalliert und wollte den einfach nochmal neu installieren. Dabei ist mir aufgefallen, dass die Ver 0.0.6 weiterhin bei IoBroker nicht als "normale" Installationsroutine verfügbar ist. Wäre ja jetzt echt schade, wenn meine Investitionen in Warema Produkte nicht mehr durch IoBroker gesteuert werden könnten. Besten Dank für eine kurze Rückinfo.
